# SPDX-FileCopyrightText: oVirt Developers <devel@ovirt.org>
# SPDX-License-Identifier: GPL-2.0-or-later

name: CI
on:
- push
- pull_request
env:
  EXPORT_DIR: exported-artifacts
jobs:
  lint:
    runs-on: ubuntu-latest
    container: quay.io/ovirt/userstorage-test:centos-9
    steps:
    - uses: actions/checkout@v4
    - name: Run linters
      run: tox -e reuse,flake8,pylint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ centos-9 ]
      fail-fast: false
    container:
      image: quay.io/ovirt/userstorage-test:centos-9
      # Required to create loop devices.
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    # We need to run this in order to fix sudo execution.
    # See https://github.com/rocky-linux/sig-cloud-instance-images/issues/56
    - name: Fix sudo
      run: chmod 0400 /etc/shadow
    - name: Run tests
      run: ci/test.sh
